apiVersion: v1
kind: Pod
metadata:
  name: participatory-planning
  labels:
    name: participatory-planning
spec:
  containers:
  - name: participatory-planning
    image: participatory-planning:latest

---
apiVersion: v1
kind: Service
metadata:
  name: participatory-planning
  labels:
    name: participatory-planning
spec:
  type: NodePort
  ports:
  - port: 3001
    nodePort: 30010
    protocol: TCP
  selector:
    name: participatory-planning